### ISSUE TITLE
Cut a new release to npm

### ISSUE THREAD

**Issue by jordanbyron** [ember-a11y/a11y-announcer#10]
Hi ya'll!

First off thanks for the project. We all appreciate your hard work. It's been nearly a year since the last release was pushed to npm. In that time some commits have been made which remove the jQuery dependency and we are keen on including those in our project. Would it be possible to cut a new release sometime soon? If there are any blockers I can help clear let me know.

Thanks! ❤️

**Comment by Robdel12** [comment]
Hey Jordan! I'm going to try and get to this tonight/over the weekend 😊 If I forget by Monday feel free to give me a ping!

**Comment by jordanbyron** [comment]
Thanks so much Robert I really appreciate it. Enjoy your weekend!

**Comment by jordanbyron** [comment]
Good morning @Robdel12. As requested I'm just checking in to see if you might have a chance to cut a new release for this project. Thanks 🤗

**Comment by Robdel12** [comment]
Thanks for the ping @jordanbyron!! I knew I'd forget (I traveled to SF over the weekend :p)

Should be released and ready to go! I've also pushed a WIP upgrade to ember 3.4, but it includes a deprecation warning that I need to clean up when I have some downtime. I appreciate the patience! 😃
