### ISSUE TITLE
didTransition deprecated in 3.6.0

### ISSUE THREAD

**Issue by tansongyang** [ember-a11y/a11y-announcer#12]
This is similar to ember-a11y/ember-a11y#73.

Ember 3.6.0 [deprecates `didTransition`](https://deprecations.emberjs.com/v3.x/#toc_deprecate-router-events), which is used [here](https://github.com/ember-a11y/a11y-announcer/blob/394fcf97a5eddcc7990eab2577bd6297079434a7/app/initializers/add-announcer-to-router.js#L14). Can this addon check the Ember version and take the appropriate action based on that?

**Comment by kkincade** [comment]
Bump here. This is causing warnings during the _ember build_ of my company's project.
