### ISSUE TITLE
Package has not been published since 1.0.4

### ISSUE THREAD

**Issue by tansongyang** [ember-a11y/a11y-announcer#26]
See https://www.npmjs.com/package/a11y-announcer

We need the latest versions to fix deprecation warnings.

**Comment by zinyando** [comment]
Any update on this? I can't install v2.0.0 on npm too

**Comment by rajasegar** [comment]
@MelSumner @Robdel12 Please help

**Comment by rajasegar** [comment]
v2.0.0 is now available in npm

**Comment by MelSumner** [comment]
Closing this issue since there is a new release.
